// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/coins/:coinId": {
    params: {
      "coinId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/coins/:coinId";
  };
  "./pages/Landing.tsx": {
    id: "pages/Landing";
    page: "/";
  };
  "./pages/About.tsx": {
    id: "pages/About";
    page: "/about";
  };
  "./pages/Details.tsx": {
    id: "pages/Details";
    page: "/coins/:coinId";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Landing": typeof import("./src/./pages/Landing.tsx");
  "pages/About": typeof import("./src/./pages/About.tsx");
  "pages/Details": typeof import("./src/./pages/Details.tsx");
};